from .types_def import T,K
from typing import Protocol

#abstract_class_protocols
class DisjointSet(Protocol[T, K]):
    def find(self, x: T) -> K:
        ...
    def union(self, x: T, y: T) -> bool:
        ...
#store_type_protocols
class GroupStore(Protocol[T, K]):
    def get_group(self, x: T) -> K:
        ...
    def merge_group(self, a: K, b: K) -> None:
        ...
class ParentStore(Protocol[T]):
    def get_group(self, x: T) -> T:
        ...
    def set_parent(self, x: T, parent: T) -> None:
        ...
    def merge(self, parent: T, child: T) -> None:
        ...